import Head from 'next/head'
import styled from '@emotion/styled';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background>
      <Main>
        <Content>
          <Title>제 00회 변호사 시험 답안지</Title>
          <Textarea />
        </Content>
      </Main>
      </Background>
    </>
  )
}

const Background = styled.div`
  background: #2E6DA2;
  padding: 1.5rem;
`;

const Main = styled.main`
  background: #fff;
  min-height: 100vh;
`;

const Content = styled.div`
  max-width: 1200px;
  margin: auto;
`;

const Title = styled.h1`
  padding: 1rem;
  text-align: center;
`

const Textarea = styled.textarea`
  padding: 1rem;
  resize: none;
  width: 100%;
  min-height: 100vh;
  outline: 0;
  border: 0;
  line-height: 31px;
  background-attachment: local;
  background-image:
    linear-gradient(to right, white 1rem, transparent 1rem),
    linear-gradient(to left, white 1rem, transparent 1rem),
    repeating-linear-gradient(white 14px, white 42px, #2E6DA2 44px);
`;
